### ISSUE TITLE
请问可否做一个轻小说文库的，有些书哔哩下架了

### ISSUE THREAD

**Issue by yuduotianguang** [Montaro2017/linovelib-downloader-v2#2]

**Comment by Montaro2017** [comment]
给个网址
有空看看

**Comment by yuduotianguang** [comment]
> 给个网址
> 有空看看

https://www.wenku8.net/login.php
感谢

**Comment by Montaro2017** [comment]
> 

看了下没啥问题，等我闲下来了再做吧==

**Comment by Montaro2017** [comment]
> > 给个网址
> > 有空看看
> 
> https://www.wenku8.net/login.php 感谢

看了下没啥问题，等我闲下来了再做吧==

**Comment by yuduotianguang** [comment]
> > > 给个网址
> > > 有空看看
> > 
> > https://www.wenku8.net/login.php 感谢
> 
> 看了下没啥问题，等我闲下来了再做吧==

希望那个插画在开头，在结尾很难受

**Comment by Montaro2017** [comment]
https://gitee.com/Montaro2017/bili_novel_packer/releases/tag/0.1.1-beta-multi-source
预览版，可能会有bug
还有java版本就不维护了，同时维护两个版本有点困难
